/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ColorTile {
    'tilecolor': string;
  }
  interface ColorTileAttributes extends StencilHTMLAttributes {
    'tilecolor'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ColorTile': Components.ColorTile;
  }

  interface StencilIntrinsicElements {
    'color-tile': Components.ColorTileAttributes;
  }


  interface HTMLColorTileElement extends Components.ColorTile, HTMLStencilElement {}
  var HTMLColorTileElement: {
    prototype: HTMLColorTileElement;
    new (): HTMLColorTileElement;
  };

  interface HTMLElementTagNameMap {
    'color-tile': HTMLColorTileElement
  }

  interface ElementTagNameMap {
    'color-tile': HTMLColorTileElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
